apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    dominodatalab.com/hardware-tier-id: "bar"
spec:
  containers:
    - name: test
      resources:
        requests: 
          memory: "8Gi"
      image: k8s.gcr.io/busybox
      command: [ "sleep", "3600" ]
  restartPolicy: Never
